// protected-data.js
// Generated 2024-11-07T13:18:48.048Z
// This file is automatically generated. DO NOT MODIFY.

const ENCRYPTION_KEY = '88f47620d87d37406c8c09ad70185d977506bbc89ef1fe1078bbcb1d3afdc99b';

export const protectedQuizData = {
  "levels": [
    {
      "name": "Level 1: Trust Your Gut",
      "points": 10,
      "questions": [
        "U2FsdGVkX19jCKRlYEVlmghsNcfGGZdG9+6p0QFmiu3kLkQD/4dxuym94ZbDTGAtjeJcK3jCkqur/7IOP6qRlDMNb2TyaehJ1Aji1t1G7rJF+7b1ztT/fJ8LQTAYbNK5oCwZHNnp5RM5QSaoaiXbKRefIAVrqjigd8F1vwihdgX25UNUZHpa/MBVMvbRmV35bHdZOPn9ybK/4sszzGpV63q2hgzEXiHWpzA4kYMsJSsy8sLs6RncEdMh6HWyWU2rT2dOtOVOSwM+k4Rdx8Rgljt+PMaHua/V6V1acd07jpOlWnHwFS/jv+li9B4BmbAPyFf5MNmz89ATURT5JBFK/0Q82sO40bF8nVESDiViuk/zb8u5OCxtCTQjjf/Ys3eaBKms4GhTOjbeM+7pjtS2mcJgea5Adzv92DmyCbMWfxx0n2EgyVFVk+KsN8+83m9KeMREtrbOG7HFsMCKTbnoBOnLOc1Hig1/Zh7M1uoStVYki3F48MF4yW3eypSZKItSh8qTifnPwRnkXcOHkwXVIraSBdojTxI7PvyZF41z1dY=",
        "U2FsdGVkX1++L7MfOwIVReg+Cc+CWx+5Z8CHNpmP6Xw5hnFPM0CU5NWpIegNqr08se3Vr3fDpcdljHSbr8lVubZXU6We5qMWLbrgXJKlvG5gzyf+GNx/u/3SArqTSAuLy58mYcDcUjcEbKzs1eai1Mgrt0gOS0kbEjoOeU7ECiwnxBYCC6vzkHzbUCOZYgQFeAE63gQooii1Z4vnL4aaQFIIqcLpSjuSist4/LYOPwPOYJSKaZ9Wo582lTYhBiAmQ5piC1qFpg52sV6+NZ9CYvDNjT5WALIJgOiWuz76JYNtX/o0sn0KqFp5JwVJHjr7SFttbxY6RPOSpTW7+6jn62MV43UbuhDxLoG/gVtYCHk8ssnF1Ae2t5odMjfroCi064elEvnehNmRqmvEG9JT8h7+Ul/qyvw2WsrKQThZhaxi8dc82je8spEJexc9OAcyAb/KJoWy5sH0uTwCpYufLdIGyngvsJymRjd9a1tlTs9W1Vaah5UDhjSLaHQJiHSJKWjVOJgBvrL6s42K78wqCg==",
        "U2FsdGVkX184kGc2P6ZIl1nCfW1xyS5bOSTecFV82CJXxJx/wwSbGYYfFw+MABm0AgbAQDVwqpaRj4N4oVluWau5utUzufGjrgaDHkS2+FY3bmynCWgAfC8RIBU9wEiJOHioVOBk1vYuACD8bCQf2mXFv1fYSTY1t5T0PIBwoxb/TI/cYY2TAcSUNCZ9BmLU09agrTXApEelbftKVOtDITSKo0+XnaPvFRQa6B8HsFZQXU7eJf9XcW24q1lsOwe6owWX2jaDJ+S7MEB3MAqVCz1NcILQOlRQkiKo0quE/7P46R4oqibrcCYsGLySNm2SHeWxacBqNPzqmIhCwZcqwagnMxoAiXED2LDC4tt7EiMRym9SvbjLD2F0sSVVkNvL26G8ZzE8bM7IS6bLdZshrXf5v3qpOej1ksiyc2KXdvwlefE+A7q78veP7MhC1TWmbISiqHNdGVzYnoHoZuZy0O5tmIqGVsEC+FUF526s/rMx8kMKXQEdZTUOUSVB4I13cu6k2iOa6U+nPaYsnc3lwQ==",
        "U2FsdGVkX1/10AZp2T1HW3pvDx0vvnDhxwn70U4SEXdH7qHKO7F6M/raxuiCmwRT1qfysyZUgHrpXeh+mTy2WLyZfC8cM1vefNZxhgPgPrMYw3E+ng46/hRyGQT8EA9ZQyfK8i5dTzOYxy/84w+tepHvycYp+hBABqJTYYx1S8AwnCRCHxSAaHSEnz0L0HXSTQdmYTl0oT4o74v9pJs6byXIh7Z44F1T5C0gOg9FxVJg12VLNusCJYQHa4j4GcjsRUrT7vSGiF1+Le3rmi1DjbZoWWd+nKg87APY1kAnVMuGrGedWh8HYKACKGJfCc5RubnIr8vvtI/BGxJvp+MqpfkwzDGZziYMPEuqtBEPcRvvpoPhGAsyyono2z3YL/bL",
        "U2FsdGVkX1957foJH9/07GVfDxARqTNIbTk9THuGyh4EuM/Y7ua6dUYFL07VXYJBUIQMl4raKyaNNMNmQLydQpXg9A+Dv0JteHUWryfzS+S2SR8Ry1QCJy979l0RSJySKjaaZooq56bamjP1+xC/IfmAzhZHwF2fO/CDL8PtYDPDtpvf4c5YbgSbH3vV6xLcXCigPVGH4DhscPqrnsZwK7N/QOaHPUWWkXTnNWvThk4hEw0Hwtv/+bisZBwYWVdp65DnoMDmKUr/p7YtaR9V7r80z/r0u9uxVRynDdpJuIuBk5EXZkvQ1+EdRh5yazxQeATo/x7NZaafzePz1La3CGEWaxI04GsNT0IWAThnlI8BTIAxaWczNl/fTXMVgJphC7+vB7dZU1kTFpQCF2QkB6vX8Oobv25ioJF/nPS5ZCkUUGYybv/iYTfz+RcM567xmvJrbsFG5b7iYyAjPZ0xTFi+KCZLsRmGUPaSXT+ct38="
      ]
    },
    {
      "name": "Level 2: More Gut Decisions",
      "points": 15,
      "questions": [
        "U2FsdGVkX19yXz8FqidJ8CjWpHLPNNTfeHX9qgXKovXWdjxdUQ5oIqsAbcdlCN3alf/D0TAqqVMGgba7xecI6GYvIFRXV8qotXCKkce/MVtbE8BcbDOCOZZE1siYBTJ/vIZyr2tiEme8BQsk7iyfA9SG47giBfMbpUqMgwRvjjebrfUo9cy6Q8ZQeGl3eYoBCBhQqcbxaEYn4PlXp3rNOa6rX3zSWjcYL1YyvhFB3EUm2n5hLvY9IuL+6Hd6VwZB7vXD8UoJ+CsLF9NUTUoJx3yGKMq+ag1u9Fd1R35hdzh/yjDWRYyNtpjgXTSkAyRxY187332XVPJ8L7SqgbgYhWPj8UQlgqKxOCRm1bO1Hd4uOgdsUAnqaZwoFwRCJF3u",
        "U2FsdGVkX18BnZM66T9g1oRA+98pvP4faczuDXbUNED8fXdJf5W1QQUk4Ln9fB9IZk2KKTpLCLCL/VCl5GVR5TsMuldcraS3Ayh9hYgwj583Wo8+MhLC7pwHqsRhdBKpLnGJXnlfaiwgkr87hbbXJgdzVW9yqAQPFRIokfvAgcwE5wuof96PIpMgs5ecIPrCrQ44783SJLMPxXNPB3VH9WjcNxpVotcmK9qxxiszxliB3pWXIYG6fzMUynuPRGYsYM5tzSGE5OAHAmU8nNOizpd1YC2UEWJi/H531X9w4jUoNq7bGhTco09uiTkjNUEdLmYsqgjy1c7JFSv6mn7WIh/XEVWTs6cR/IWXJhRBjUryoDa9niME/6SV8U1e8I/qLQVrRzqfOTpBkSXWQ50s6qht0UffGq/nODTt8gV0AdO6yJOSVAawVfBjcTiVWuwR",
        "U2FsdGVkX18R1IXNcxUpqt6BTeMIRZTvhwqHXSKejiTy9Y3C5eAAU7XQw45i4KOHe3YAQKaSDf4r0E0HeDuuvfknifx67vbgtdA+pPraqQwSIqdZ4S/TeERufMKICW9aKoJCT74/SC6RBkhBBIUQtdEf4Q8QraSzMdzlaxmxp21zVqG/sF7VxOhHlKcD0J38EwgbRPOznWSyDzIkry+Q34R8k8uWKHqKZTQ0I3ECUgccdWyeYx05gkuIzedjsIgVdTOLNCHyqwIuFOgFvaIz6od8+nSzlEfi2GFwP1WFbNaoPdCBvbDsR9b85wZLZ5UbjJejPM47zpOJVNGMOlIZIc/BOAMeSlYxm8Kj370k+CCygcenWXHniGb7jEltMBNfHzjfcDnh8nRirLciKPLYm65AdNQUtQD7YwHaGzifnCLUEit/LLXPiZBa4Ic8V1g1",
        "U2FsdGVkX1/HjyyHmvlsbJ11+l40eGJYT54oLO++VuN9hKn0q/1zfobnPBD0TedfwicktBWGItRWTCJSKF3qQxk7dQhSiAP5SqeGlRfFDgWsstqjpDG57ig4xM1twElTeBxVsrI2a+OtjO6F985zfI0LKTzqITrYlRJpfhFctOavYRNVnQKMWVszeubEjMToI1zPsGg2KG9KKZ8XHAHHQQZ+Jm9fgiyGrMZEl9OC0QPA/QKu9cTz1KpZyNYjQbEZhZNlbtoAnUzvBzyMyOTW/piyf9s0HrVqY+PzHElWVeBYMy0MIxssxPIadADGsrzFX7i00BuC5EoXczp1w+qNKIbfXpVVnrld/0JnhLF6HuTLcSOxsLCgEwBXi5lEH8/Vd/ZFgXRjnVIMFBEHkr+/sw==",
        "U2FsdGVkX19g8QJqmTxdk3yms+fNA5jXKB8C7RNY4Xz5D8UmZobZqdjhX+VqU6eEn1XO8XOqEIUhhdfKbwcGPBr6JuTHY2G+tuudXda+XacTseW9ULFYXNQdaEgcpkGVNlodVZV/YoUg/QWhi7Qy/pD9qWKI9E6ehc1qcg8VOVezWGnVGdWp+YdNkRycFm9nEodOfEkoresxiBl4A9+4c21WVt3yfFPxpAjjP1WIKy4kHwBYj1G7TAjECDWBog7wFCuNYL01P8hnfxH3Wb1T3rQVg17krVQzWtWeMy+7JmLsMg6W+b4reWdhZVAzpEMRhJQwO1JVvRNb9y7Auv6O3oWmcgHeWVCQoHMJ8nW6oyoVuNguA9OYbagbJnhW34SaV7d/05jPVQ13s7f0daVMeQ=="
      ]
    },
    {
      "name": "Level 3: Spot the Issue",
      "points": 20,
      "questions": [
        "U2FsdGVkX18Lw5GZP2Kl3D4t0r9zppuV9B64TFsddeSxMl09kPahaGnOIUVH8ghWvQUehl6tzjko9fmaJhaJQsbKTS52eUJ2sIo/jbHMkOR3Da/T/M7W+L0W+ssqOnXxQ99cbulRAGWlqplHgTOhFK8jHS6O8vIhvLSG99c4NBkZh/JyR/Hy2gs9/YcRBVXcBIGbxhzPzNBdoHW2YWyZpNHbF3MlpOaPRCwfgb1V1oniA2+IDNqB38p00j/3w8/xzdKt7WLnLZAz45zIAlG1PReGMavBcbsEYTJXKBrM8ot8jxO7UB7CNqMJ6j/0+WR7uLHU9tqrEUGFLI7UsldLV0hPp11Fc62mnP9O8fF5izzY6+FVBBPSyqb+gADQYuITkE6fCcnIr0Xau4JZaWZp0EFVn9QLi21pgcb9ebx1jWqrSSriDJvb2MHFKOAUUXtE+M77dFxV5w9/NnIRkrL16736X7mEBJPhLYWyHotJSIg=",
        "U2FsdGVkX19EzVnhB8azRfaUwdSBlp0s+OsUh1R2b27Wb6+9XEAMXRHWWsn7ItQ8jMd2iBYNPtmjnOO8kKV7pFM25/Mlus9lYiU+FYB2DF03ZvI1uhn0dsmCTdCzfH6m78n/heoXH2o7dIXdOPQGUPsasax5usrMKCOIybmWHah/UMKY3HKhhSQQ3j5IIz2IEQwUhOz0YV3mqxO0AtYBs9BBoVF213qH8DGc4s29eKnAoikcPplzfRg+D5ncucmQ9YclempIbWJuOcTL2yn4PDzqZNzwPWN4j9q9Xg+lhPKykCINlws4DorepWl5o6oA0hk0qZneiNHcvkLKgmyLC3/3J5BmFo2sGdgmn8TAWrWexFsVyWbku8dMT1suBcN4K/l7lkvU6qCWzXnT6bkgLbbuzohASqtbUcVcTnv/ieQyVqtU08uaRnmi5qZjq5Dpznyt2+vK99zct3Gxg+3Ruour2HiSX3OhQ5FF/6KSxmM=",
        "U2FsdGVkX1+on8zCNJbJFxKNMXGuAqqDL7KJDKBQzbFpGb1QVrgSOqHLoLec498iLnz70l8XEPzH5/6bmTctDSX8YEvfZEWQPNRaxz49Unkv3OuXCSBNquWhOaPnr6kUnWOgtwzWkcWyUQcR4v12p97ckkZDPc5CExyOsjPMdZXMsCw5O4DHZWDXapRSg4CJsmSiKxf9XpuFmK+J3PjNnEVRSRiuj1u/MPk8Is5QGj+Duwy0QXO5ONfODjoyF9U7rVNjHv3GLbv2OA+tDqoec/o674/mGKQTjUDP/SiaMiHW2GJGNc/lXRDScSdRjkHWRAI+snIVdE+Si0r5Hbc8oHJA4bIpH5B0OAIVkgk8RvBeaR1LswNVTnNGfRPC/rH7WaqXPkO7EB3Prw5tBpBAorKn65jfFw9ZwizK+kV07AI=",
        "U2FsdGVkX1+wO7u3bJa6CTJmGg+oAsSHT8KpT7oWK0vQFE/ySnGAC+nWh9jL15EI9B9MXLKmD4Uvs47xuY8GPCZuQu4PIycniuGHEhAdY3dio593p3F0X14WpKM2Ag2pvs2rfDNJOL1NjN5QOAOUF+4Nv3N77DHSkjvw9mLpTkzG8Z5tK4V3wvIo4URxPIeB4wacM3XvB+2J0EnS5w9PSlSv+NVrb9pyMaKKzaB+2D16ABJJs1VDFIqbrAofgdiNQCze2yj944WFUdEIQk3iXKtYfdehr5V7nb+gsvR826Gcr1fMoHo63arfaz4el/aXkC5qA1spahPJzgQ23nO0/rpN/Ze66lFnITpoMdAPrYhOUdArn0lRq1JYPqyb5xAU8ma1uYRXzJEsXiojuiQ5LJAtIdC5emHaOIH80Rax1g0=",
        "U2FsdGVkX1/biYHe1aJUNOkFO+/HYCa0FMTpboSi29PVeC5IqgEaaIJtHgiJO5zQv9Qz+1fioh6kGLv1omNrsHICsbmXHdIGMo6zyZ0H0nJWf9THiM9zO9f3ickMtfriXPLvJEjj/na3Sa6UnVL8LlT/4cD7iY0CC8bBzyw/Z0kmclSjBa4bSXqKQNkRt3kQ+tsXmAp7oT9X5cZZSuzT+0vWe7GTQUeej9EEp4QUUMJl2Jbw2oP47SdCpcHqZMBSlfGa9FlzsYveaJE5JR2S351LGhrdqmG1k1bSpEdOhWK75YBXzvmaClIzP7ssV3qYrAmchDZMrbUgE6LIVS1kET4sImwj4haXF7F/WX9+0/ecgTMfmtIcop1ex3eCerOwTmW4zNaTh9o50l8KTjAWMc8ab3apfs9HiropCSIc5BQ="
      ]
    },
    {
      "name": "Level 4: More Issues",
      "points": 25,
      "questions": [
        "U2FsdGVkX1+v5qspobk1PkYzS2kJr/3UvOKJiQKKLC/TFlxa/+uZgemgM20Q2EFvw7VpdspIPJJ+UAw/BY1OMLIrBBubLwH4+FvXUde9o1AGUzFMbvsX6AkU1W0vEtLW5164lKWVf4yE1F5eDt88P2JJ9xW6KK9t8djxfIGysVZ47Uvt54+sWUHTipioxwgW49IKCDGSykXMfVV1uCpqDADmVrnXCTXc+Tn8guOYZECX7K/6slhDIPDjtJ7ycCiOgD5jlnkKOCMAY8dgf6R5okGapY5KzfvZlRGqLDTKZ+ohxDtNJe3mVnGWd6ac3KYsifp9PQie/4I9kjG08yRxtxeidGuxsR2MSkEufZQXGBGil+76RvlYgh+p0PNmXmraz72WisM3kL4StkYAMRY4pVi8sILJDFlqTO/UskHvA8ww1FYPgei12wtr8CledgZH",
        "U2FsdGVkX19VHaPysBoxVE/zqduEE+bRVy7ZtMpSonATCrEKoviK8g4rQphlJDFRGTyKoGZPP0mYyY2WJog5MJHzLI5xBpVwTIgAz/o9d/58RGehHUke6uzTM/bf8IjQ2KEIGPILLatIc7iUmCdvZP9JQ5TtLw7TUa4wGILJPdot+y+AXEAgCLugvOlGJK9Yxv/Gv4xEbXkWF7/jvDCypjOQzaTVLLBFtqhZasrMipEMt8YeBLtmbxhZE9xk2aXvHgxaOVW0HmsAAG4igJKK2/dt+f9AmTWLVac8WdR3sGxAPZXnOpnDfd2ygHKOwJvVhmtgjDiGoBm4KqofQKKpMwPqHsPHTehSzAMsEyKPHloDTDhjPGkULFu9YRNHBfOFpmN6hKzgrfdzAaZWBBYLN/YvYsVA15vv6265Cn8rKow=",
        "U2FsdGVkX1++bDn08tZTudJBZ4QshBfv+ROAFf5WbV0ZNWL4yWOfRQwSzlwYyRQhmjC5UaRKqu+MIyMMTCsVlgkDBx3tCHlzovZB8aRrPivqSXNkFhdAgTvrj+xRws0tO5GWs8NGIXHE5Wr9kd5JpI7aCTwGRFuR2oMbPir/0+RubOBgG4CKtnh3Vz0XBGiH45KcK4ugQtaYAssF9b59hG9dFtRUo+FbPiGrvq7FIptPNEEf0n4RbtWG03gQEhWZzdMgnhJowPwifWrvz7YeLngY3hIt47nIrP7aQoNYgTiKWjFTycFBAWAgTLk0jTFpah6FbMjQOVZAD+Igf7MZQn2hdNWH7vWtsh6++IVFxoRZTAoOH3JWD/11XqBqonvV50HJxRf0EQmxMPOclEQbiFi/0Lu2BKNqdB+pDvKhv2U=",
        "U2FsdGVkX18wioG2qqQ4RZIJ0nJQDkTNYqmPNcG0oFVlawUmp0d+Dp0sS0+UNHgg1SDa1F+yLVViHVflTGfEBySYr5TbJbP0GJ8z9jIV1Vg6sR8YkTo9RSm2UUoyI3SNcV5N4krkicypHYszCYyqiaXYI3WOv79NaJa7elz9I1oWKXiZtS9ZWV3TO8EoRge7IojrN9E4KMqo2H5XbitTw3ndylkb09GQkH/irZbeXZPGNVkA+x+5/wX0MAk4cwPWTy9SF154tlyjh8IoMm0VREaSc9f0+xGNBDFMqUG+3DcqS2rpfqBHQbQxyFOARUEcG1l0sB4mpgWLDK52BXwZBbvZxOziyxtTMVwbtzZ7+JSo7+JLV+A4mK/McpybuyUb",
        "U2FsdGVkX19u6t86KoanPLl7EvVtXY0Z+33dt0xPkVnj7QhMQHOAu66u7YQyWZfBKvs+ocOZrcHTtE3YkSFPw75cmJutwvnmcZ3r9+53Du59gN0m41g+LffWfYbjqVUSFcw6tb3nGBzxR1KGN0LRC/KZ1NKMk67fH3+drWCi2RShNAKh9wG091GSLyGg1/jqy5GQcaOsQTqbfikH8M9lxT+w8W+gKRfByxR7pPV78PgUSprIHEkuOtJuuTxvHWILtV0tQ2O/p8EhScnSsoWgsM0w20L+j+wqMS5mTjDgMUgfRmzIsiI+Lc2ZruxBKk955Em02TaZWc+jjEkyVat7MQSPKGiV6qNGTIur2eu/LsZ1hB9YcreAB8aXltwcKU/MXmJPxLZ5/8dzA1wEWTcba0vaCTP0A1PJdlE1JoggROs="
      ]
    },
    {
      "name": "Level 5: Problem Solving",
      "points": 30,
      "questions": [
        "U2FsdGVkX1+1EvJ5Kq5/K0L0sChkPo2ff1JxElQw6VFjvRfEsywj8AFPKH+MWupscnZtBEF0ygv7N+XlSTbhPum2t7UQK7XxiSGXeQw+Ej6SM5FpNugw1tHJOc1P7sPBytzdRyqhXzVwCkypmTAj8ZyqELGyQnza407NUITSXYGv1CaWNVzpCuu5PLakJK9ZcLQoOsoV2IxLQ+/w6V5x5R9or9SMBTbfXrswqBYV3kQsERxxt0pueYPU8RKgV1Ttdwpu+gvHNOqrJ83pdUqL/eo/Q6uBiZ2eJijf4d12PU2IIThezaOBw291IarjYNnELxJMhT+KV+rKC+XOqXORxoGIergpQ0ZnhsV2Dwn370FfdIOi+oXPBv4GFsf6jhxQsedeRctJhHuHJluTcYjAT4rrHxlOgjiwwvKzNewEFF0=",
        "U2FsdGVkX18r9s9CI6tnVKQRtA0hcTbYjBAOSEUKGd7SDz+8sr0+xL3FS9/JWYGo/dWn8EX4UO5hBDHysfYuLq/ZzkLJh9PTDymZsj/PPi1jU6x8Bv2kSTtzFft2hlRNS41lXf/R/VbHfaBAWQXKGX9fK+YPt7NzaIvM6CoBQDD1iV/j5DTWlm4/JjdPItg1P5wCS3uZZux/XjIJjS1ooBuz3KbDyzKwsivjlG5BEl8zSjGjthSGWy324YI2x36Gb86h6uxWKwiqOzh9uZN9c+vHfCmU9x/OfyN76j2/TbxqA5B5xtjmo6CdpysO1XEZyPMSCAbpTGFUPzaq2ItAOlnGb1hWvwwqtzUIYyoGmuZhb0nXbL7deVhFSuDWFwSKukwJbuAKguU46+0UzrnUG7i1gklFofgJLQhTO83UNdLklo19jopwnjCegTc5P84j",
        "U2FsdGVkX1/r7UMOisJGJZTWX5FkcJwm/XUKNFB610sIi3P/DQHVLri5cIAfpIPIXiuCfipLvGgnPXKStKGzFkrFIjQsVdtRvhI13AOOaXvdFS/B2GTFaqijME1D0xH0OUE8bYIy5crvWfVJSh82cv6iTtK9m2WO9rgSZRrsEi2cn5XwlXPo7kbmdl3bVC9layH3LglmxmF7E1Z1B3Jjsssz71bQVCaHnWnrImJSECbLN7zpT2u767qryvvVYGGR9TF7RV1VZCZUB1MVvmvq7z/ZId8Z65HYHlSDq/8KrT0fSYu1wBizFYODFGdu4TrGChy45PnyjETwXAaytP5VrehNAKjNsbn+AKdxzAPekdWD2ANIrphB10mwAgN7r/UlBKVe3d13fsZEspo2TEb/jw==",
        "U2FsdGVkX1/zRM4F6YX+4VaMxeP8eEcI5gVk8g3LVNjH/8VD9ORQBNp9NpNtLhvoWFvmFziA99wI9zEcJxo4xhq+Dh6AzR4yOht1+ty0n2l3hMjH2FTjiGNWUWm9AlKev2AxjGuyT32xipvakUVV4DHDIcWZ8ihB2amqvb1LfD3ElutC2bv5K3ascwUMoy+1FK66VKOC9DpbGub+DRao6q1CiWkb//fLvLcXXMzXr18nEFxBgSRsj9aAujdlp1d4c09i7VGwLLhfAzY7/rtRjiOTUiUVr/Qa0Su325Bgp6WgWF8v+QGMBhH1UaTpVghGURJVKjq/DJMD3MLejeFEugC8rCdyLRSCsAVtIAa329cV+sjp49nUORM4EqtbRauP",
        "U2FsdGVkX1+aLKAtmCC42l/FMjnd2r60F3v6W3Uam8LvPGsFXKIOlib6gkIJuB2Sg5HOAZktiUQ/UJXD6nOQJUSPy0W1LWuqZpKESxV6D3DRf+LwNyJ1skdP5vwDcsUa+0Qt6appXkc+h4dhmFHo0Trl2RKcEFiPZIjUB5qoqdGkAqMLwLhbXSvMMdiLGC2j5PwLZ+GwwgFbIg+FS2Y0EGmyswB4YN3IwrkXQOfcuNMv9aZE7Hzk90jhaAdJGDw3xcIMWA7LgHoHj+1pNllBEG7LSlr7dGJzpIc++F1QJSpa7+bNoFPEOe65m9fkGZv0yW50wHRiKzdLBBux0wdCgfOVOdq5if33btY+5ENlYFfHNr5QbpRrLmIURlAsnZO7l70VG4UcUY0Nd4WYdvNhhQ=="
      ]
    }
  ]
};

export function decryptQuestion(encryptedStr) {
    try {
        const decrypted = CryptoJS.AES.decrypt(encryptedStr, ENCRYPTION_KEY);
        const decryptedStr = decrypted.toString(CryptoJS.enc.Utf8);
        return JSON.parse(decryptedStr);
    } catch (error) {
        console.error('Decryption failed:', error);
        return null;
    }
}

export function verifyAnswer(encryptedQuestion, userAnswer) {
    const question = decryptQuestion(encryptedQuestion);
    if (!question) {
        return { 
            correct: false, 
            explanation: "Error verifying answer" 
        };
    }
    
    return {
        correct: userAnswer === question.correct,
        explanation: question.explanation
    };
}

Object.freeze(protectedQuizData);

(() => {
    Object.defineProperty(window, 'ENCRYPTION_KEY', {
        get: () => undefined,
        set: () => false,
        configurable: false
    });
})();
